<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC9fwoqz\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC9fwoqz/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerC9fwoqz.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerC9fwoqz\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerC9fwoqz\appProdProjectContainer([
    'container.build_hash' => 'C9fwoqz',
    'container.build_id' => 'bb8c6ab3',
    'container.build_time' => 1643121017,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC9fwoqz');
