<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM7caxry\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM7caxry/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerM7caxry.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerM7caxry\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerM7caxry\appProdProjectContainer([
    'container.build_hash' => 'M7caxry',
    'container.build_id' => '0cbe06e8',
    'container.build_time' => 1643121127,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM7caxry');
